-- ===================================================
-- CBT EXAM MANAGEMENT SYSTEM - DATABASE SCHEMA
-- ===================================================

-- Drop existing tables if re-running
DROP TABLE IF EXISTS student_exams CASCADE;
DROP TABLE IF EXISTS exam_sessions CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS classes CASCADE;

-- 1. TABEL KELAS
CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL RUANG
CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    capacity INT DEFAULT 30,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL PENGGUNA (Admin, Pengawas, Siswa)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'proctor', 'student')),
    class_id BIGINT REFERENCES classes(id) ON DELETE SET NULL,
    room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
    exam_number VARCHAR(50) UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABEL MATA UJIAN
CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    duration_minutes INT NOT NULL DEFAULT 60,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABEL JADWAL & SESI RUANG (Token dikelola pengawas)
CREATE TABLE exam_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    room_id BIGINT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    proctor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    session_name VARCHAR(50) NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    token VARCHAR(10) NOT NULL,
    status VARCHAR(20) DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'active', 'finished')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABEL SESI UJIAN SISWA & TIMER RUNNER
CREATE TABLE student_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES exam_sessions(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    remaining_seconds INT NOT NULL,
    status VARCHAR(20) DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed', 'submitted')),
    UNIQUE(session_id, student_id)
);

-- Indexes for performance
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_sessions_room ON exam_sessions(room_id);
CREATE INDEX idx_sessions_token ON exam_sessions(token);

-- ===================================================
-- ROW LEVEL SECURITY (RLS)
-- ===================================================
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_exams ENABLE ROW LEVEL SECURITY;

-- Allow anon public read/write for demo client (Full access policy)
CREATE POLICY "Public Read Classes" ON classes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read Rooms" ON rooms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read Users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read Exams" ON exams FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read Sessions" ON exam_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Read StudentExams" ON student_exams FOR ALL USING (true) WITH CHECK (true);

-- ===================================================
-- SEED DATA (DATA AWAL LENGKAP)
-- ===================================================

-- Sample Classes
INSERT INTO classes (name) VALUES 
('X-MIPA-1'),
('X-MIPA-2'),
('XI-IPS-1');

-- Sample Rooms
INSERT INTO rooms (name, capacity) VALUES 
('LAB-KOMP-01', 30),
('LAB-KOMP-02', 30);

-- Sample Users
-- 1. Admin: admin / admin123
-- 2. Pengawas: pengawas01 / pass123
-- 3. Siswa: 2026001 / siswa123 & 2026002 / siswa123
INSERT INTO users (username, password, full_name, role, class_id, room_id, exam_number) VALUES
('admin', 'admin123', 'Administrator Utama', 'admin', NULL, NULL, NULL),
('pengawas01', 'pass123', 'Budi Santoso, S.Pd', 'proctor', NULL, 1, NULL),
('2026001', 'siswa123', 'Ahmad Farhan', 'student', 1, 1, 'CBT-001'),
('2026002', 'siswa123', 'Siti Nurhaliza', 'student', 1, 1, 'CBT-002');

-- Sample Exam
INSERT INTO exams (title, subject, duration_minutes) VALUES
('Penilaian Tengah Semester - Matematika', 'Matematika Wajib', 90),
('Ujian Akhir Semester - Bahasa Indonesia', 'Bahasa Indonesia', 60);

-- Sample Active Session (Token: WXYZ89)
INSERT INTO exam_sessions (exam_id, room_id, proctor_id, session_name, start_time, end_time, token, status) VALUES
(1, 1, 2, 'Sesi 1 Pagi', NOW() - INTERVAL '10 minutes', NOW() + INTERVAL '120 minutes', 'WXYZ89', 'active');